version: '3.8'

services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - product_service
      - order_service

  user_service:
    build: ./user_service
    ports:
      - "8001:8000"

  product_service:
    build: ./product_service
    ports:
      - "8002:8000"

  order_service:
    build: ./order_service
    ports:
      - "8003:8000"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
